pipeline {
    agent {
        docker {
            image 'ruby'
        }
    }

    stages {
        stage('Prepation') {
            steps {
                sh 'bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'rspec'
            }
        }
    }
}
