pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Prepation') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
                junit 'api/logs/report.xml'
            }
        }
    }
    post {
        always {
            junit 'api/logs/report.xml'
        }
    }
}
