# frozen_string_literal: true
source "https://rubygems.org"

# gem "allure-cucumber", "2.13.6.41"
gem "watir"
gem "cucumber"
gem "rspec"
gem "capybara"
gem "selenium-webdriver"
gem "allure-cucumber"
gem "site_prism"
gem 'report_builder'
gem 'mongo'
gem 'httparty', '0.18.1'